### ISSUE TITLE
Volume sensitivity control

### ISSUE THREAD

**Issue by waxlamp** [mikecrittenden/hand-me-down-for-google-meet#1]
I love it! Only problem for me is I have to sort of yell to get the volume watcher to hear me. The "problem" is in [this line](https://github.com/mikecrittenden/google-meet-hand-lower-inator/blob/main/app/scripts/contentscript.js#L93); ideally, I'd want to have some control over that value of `0.03`.

I'm not sure of the canonical way to add user settings to a Chrome extension, though a really easy way would be to expose a function that allows for setting that value from the console.

A related problem is that I don't know what units that `0.03` is expressed in, or what its range is.

Thanks for creating this! It's a problem a lot of people have, that no one else has yet cared to fix!

**Comment by crittermike** [comment]
Woohoo! I increased the sensitivity in ac46fdd5. See if that works better for you once you have 0.0.2 instead of 0.0.1. Long term I'd love to add a settings page to customize the sensitivity.

**Comment by waxlamp** [comment]
> Woohoo! I increased the sensitivity in [ac46fdd](https://github.com/mikecrittenden/hand-me-down-for-google-meet/commit/ac46fdd50a0af4db44038d9209323afd83de1b3c). See if that works better for you once you have 0.0.2 instead of 0.0.1. Long term I'd love to add a settings page to customize the sensitivity.

Thank you! Have you published 0.0.2 to the chrome web store? I still see 0.0.1 there.

**Comment by crittermike** [comment]
Yep, I submitted it, but Google needs to approve it which can take a day or
two.
